---
title: "Birds of a Feather"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: no
  word_document:
    toc: no
    toc_depth: '3'
---
\fontsize{12}{12}
\fontseries{m}
\selectfont

\setlength{\paperwidth}{8.5in}
\setlength{\paperheight}{11in}
\setlength{\voffset}{-0.5in}
\setlength{\textheight}{10.5in}
\setlength{\textwidth}{7.5in}
\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**What:** In lieu of/in addition to the standard JSM roundtables, the Section on Statistics and Data Science Education is sponsoring Birds of a Feather (BoF) meetups at the 2019 conference (July 27 – August 1, 2019). A BoF is a casual meeting of a group of people to discuss a topic of common interest. Like a roundtable, there will be a leader, but everyone is welcome to participate in the discussion. Unlike a roundtable, the BoFs do not cost money. 

**Who:** Anyone who is interested! You don't have to be a Section member to attend, and no sign-up is required.  

**When:** See below for meeting start times. Typically, BoFs will be an hour long, but of course you can continue the conversation if you want to!

**Where:** Interested parties will **meet at the stat ed booth** in the conference center and either hang out there, or head to another casual spot. 

(A one-page printable version of this schedule is available [as a PDF](https://ameliamn.github.io/JSM-BoF/BoF_toprint.pdf).)

# Monday, Jul 29, 2019 

### 12:30 PM  **Visualizing Visualization Education** 
Jo Hardin (Pomona College) 

As statistics educators, it is often easier to focus our teaching on methods instead of communication.  And while many of us understand the value of good communication, actually *teaching* it is difficult and outside of our comfort zone.  There is excellent work done on the science of visualization / visualization education (e.g., the grammar of graphics), but the work has not yet been fully infused into the statistics curriculum.  

The BoF session will focus on ideas for teaching visualization at all levels of statistics.  We will share resources, activities, and lessons learned.   Questions might include "What does data visualization in a statistics class mean to you?" "Have you ever taught data visualization?" "What was successful and what was not successful?"  "How can visualization assignments be assessed effectively?"

### 12:30 PM **Preparing Students for Jobs in Industry** 
Jamie Perrett (Bayer)

For educators and/or administrators of degree programs (or certifications) related to statistics and/or data science. Discussion of statistical topics, technology skills, and consulting skills needed to have an attractive resume and to be successful in industry. 

### 4:00 PM **Jumpstarting Early Undergraduate Research** 
Peter E. Freeman (Carnegie Mellon University) 

The session is for those who are thinking of providing opportunities, or have provided opportunities, for statistical practice to early undergraduates: freshmen and sophomores. Basically we will discuss best practices: what works...and what doesn't.

# Tuesday, Jul 30, 2019 

### 12:30 PM **Teaching (with) R**
Mine Dogucu (University of California Irvine) and Anthony Scotina (Simmons) 

Many instructors teach (with) R in their statistics courses. The goal of this BoF is to share experiences of using specific tools (packages, server, Cloud) in the classroom as well as any pedagogical tips that have worked. As R grows, keeping up with new packages can be a struggle. We will figure out ways from each other on how to keep up with R for the statistics classroom.  What are best practices for introducing R to students with no computing experience? How can we incorporate R in a typical lecture without taking away from the main goals of the course? Does R have a place in in-class exams (besides reading R output)?

This BoF is designed to gather instructors who are advanced R users and as well as instructors who are new to R or considering switching to R.

### 12:30 PM **Teaching Survey Statistics and Methodology from Total Survey Error Perspective**
James Wagner (University of Michigan) and Stas Kolenikov (Abt Associates)

This session is aimed at instructors of survey statistics, survey methodology and data science. Survey statisticians have operated within a paradigm known as total survey error. This paradigm leads to a close examination of the process by which data are generated or collected in the search for potential sources of error. Using this approach in the classroom is a useful way to teach students how to examine the quality of the data they are analyzing. We will talk about classroom experiences and strategies for teaching this approach to data quality.

### 4:00 PM **ASA Section on Statistical Education Mentoring Program**
Jennifer Green (Montana State University)

The Mentoring Program of the Section on Statistical Education connects early career statistics educators at all levels with experienced mentors to provide career advice and mentoring to help participants achieve their professional goals. Come learn more about the mentoring program and discover possibilities for developing new mentoring relationships. New and current mentors and mentees are welcome and encouraged to participate! There will be time for mentor-mentee pairs to meet and chat.

# Wednesday, Jul 31, 2019

### 12:30 PM **GAISE 2016, Statistical Literacy and Confounding**
Milo Schield (Augsburg College)

The 2016 update to the GAISE guidelines recommends including multivariate data, multivariate thinking and confounding in the intro course.   We will discuss four topics: 1) Can/should we include multivariate data and thinking in the regular intro stats course?   2)  Can/should we include confounding in the regular intro stats course?  3)  If we were teaching confounding, how can we do this without creating cynics?  4) Do we need to offer a separate statistical literacy course that is confounder-based?    As background, read ["GAISE 2016 Upholds Statistical Literacy".](www.statlit.org/pdf/2017-Schield-SERJ.pdf). 

### 4:00 PM **Software Choices in Introductory Statistics**
Kelly Bodwin (Cal Poly, San Luis Obispo) 

At this BoF, we will share our experiences using statistical software of all kinds to help teach introductory statistics.  We'll discuss how and why we made our software choice, how it was used in the course, and what the results and feedback have been like.  Come share your knowledge and/or pick up some new tips and tricks!

### 4:00 PM **Pair programming approaches to support team based learning**
Nicholas Horton (Amherst College)

The computing education community has long acknowledged the value of pair programming as a way to build more reliable software.  How can we exploit these approaches to assist statistics and data science students to undertake reliable and reproducible analysis and workflow?


### 4:00 PM **Online Teaching**
John Steven Schuler (George Mason University)

I personally teach statistics online. In an online course, something is certainly lost but it is also possible that through a smart use of technology, something else can be gained. Thus, I suspect this would be of interest to all teachers of statistics both traditional and online. The use of software is unavoidable in the teaching of statistics but the question of the proper use of technology in teaching statistics is much broader than this. 

